import { Lato } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"; 
import { AuthProvider } from "./context/AuthContext";
import { StoreProvider } from "./context/StoreContext";


const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"]
});


export const metadata = {
  title: "LIQUIDO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased`}
      >
          <AuthProvider>
            <StoreProvider>
            {children}
            <Analytics/>
            </StoreProvider>
          </AuthProvider>
      </body>
    </html>
  );
}

